
# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    - name: Build and test for iOS
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
      
    - name: Upload test

#    a
#    - name: Build and test for macOS
#      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
